name: pygsflow continuous integration

on:
  push:
    branches: [master, develop, builder]
  pull_request:
    branches: [master, develop, builder]
    
jobs:
  pygsflowCI:
    name: autotests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11","3.10", 3.9]
        run-type: [std]
        test-pth: ["./autotest"]
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout pygsflow repo
      uses: actions/checkout@v2.3.4

    - name: Get branch name
      uses: nelonoel/branch-name@v1.0.1

    - name: Cache Miniconda
      uses: actions/cache@v3.2.4
      env:
        # Increase this value to reset cache if environment.yml has changed
        CACHE_NUMBER: 4
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.run-type }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('etc/environment.yml') }}

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: etc/environment.yml
        cache-environment: true
        cache-downloads: true
        create-args: >-
          python=${{ matrix.python-version }}
        init-shell: >-
          bash
          powershell

    - name: Install flopy and pygsflow
      shell: bash -l {0}
      run: |
        if [ ${{ matrix.python-version }} == 3.6 ]; then
          pip install flopy
        else
          pip install https://github.com/modflowpy/flopy/zipball/develop
        fi
        pip install .
      
    - name: Run pytest CI testing suite for pyGSFLOW
      shell: bash -l {0}
      run: |
        cd bin
        chmod a+x gsflow
        chmod a+x gsflow.exe
        chmod a+x CRT_1.3.1
        chmod a+x CRT_1.3.1.exe
        cd ..
        pip install pytest
        pip install pytest-cov
        if [ ${{ matrix.python-version }} == 3.6 ]; then
          pip install flopy
        else
          pip install https://github.com/modflowpy/flopy/zipball/develop
        fi
        pip install .
        pytest ./autotest/ --cov=gsflow --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.5.0
      with:
        file: ./coverage.xml
